### PR TITLE
fix: accessibility issues

### LINKED ISSUE #442: [BUG]  accessibility issue
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

There are some issues regarding accessibility :

- Buttons do not have an accessible name
- Background and foreground colors do not have a sufficient contrast ratio.
- Lists do not contain only `<li>` elements and script-supporting elements (`<script>` and `<template>`).

### Screenshots

- image

- image

- image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Fixes Issue

Fixes #442

## Changes proposed

Applies a set of accessibility touchups to address issues detected by:

1. Running the [aXe browser extension](https://www.deque.com/axe/browser-extensions) on the page
2. Use a screenreader (e.g. [macOS VoiceOver](https://support.apple.com/guide/voiceover/welcome/mac)) to navigate through the page

## Screenshots

<table>
<thead>
<tr>
<th>Mode</th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<th>Dark mode</th>
<td>Before dark mode screenshot showing not enough color contrast in some text</td>
<td>After dark mode screenshot showing enough color contrast in some text</td>
</tr>
<tr>
<th>Light mode</th>
<td>Before light mode screenshot showing not enough color contrast in some text</td>
<td>After light mode screenshot showing enough color contrast in some text</td>
</tr>
</table>

## Note to reviewers

I've left comments inline explaining each of the touchups, with links to more resources. Let me know if there's anything else you'd like clarified. Cheers! ❤️‍🔥 

One more followup would be https://github.com/tameemsafi/typewriterjs/issues/182.

### CODE REVIEW

File: components/BackToTop/BackToTopButton.tsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ export const BackToTopButton = () => {
       <button
         className="focus:animate-button-press rounded-full border border-white bg-violet-600 p-4 text-white shadow-xl duration-300 transition-colors focus:ring group-hover:border-dashed group-hover:border-violet-400 group-hover:bg-white dark:drop-shadow-[5px_5px_8px_rgba(124,58,237,0.25)] dark:group-hover:bg-[#101623] md:border-violet-600"
         onClick={handleClick}
+        title="Back to top"
```
Comment (JoshuaKGoldberg) [inline components/BackToTop/BackToTopButton.tsx:50]: When an image contains no text description, neither assistive technology such as screenreaders nor crawlers such as search engine bots will know what the button does. Adding a `title` is one way to indicate the purpose of the image. This holds true for buttons whose only content is an image.

https://www.w3.org/TR/WCAG20-TECHS/H37.html

File: components/Cards/Card.tsx [hunk 2]
```diff
@@ -8,11 +8,11 @@ const Card: FC<{ data: IData }> = (props) => {
   const { name, description, url } = data
 
   return (
-    <article className="z-10 h-full w-full rounded-3xl border border-dashed border-violet-500 bg-gray-100 shadow-lg dark:bg-gray-900 dark:text-gray-300 dark:shadow-sm">
+    <article className="z-10 h-full w-full rounded-3xl border border-dashed border-violet-500 dark:border-violet-400 bg-gray-100 shadow-lg dark:bg-gray-900 dark:text-gray-300 dark:shadow-sm">
```
Comment (JoshuaKGoldberg) [inline components/Cards/Card.tsx:11]: Color contrast of `violet-500` isn't enough in dark mode. Not enough color contrast means folks with limited perception, such as screen glare, low quality monitors, or personal vision impairments may not be able to read the text.

https://webaim.org/resources/contrastchecker/

File: components/NewIssue/NewIssue.tsx [hunk 3]
```diff
@@ -5,7 +5,7 @@ const NewIssue:FC<{}> = () => {
   return (
     <p className="pt-6 md:p-0 coming-soon">
       <span className="text-2xl">Be the first to add by creating a GitHub issue</span>{" "}
-      <span className="animate-pulse text-2xl text-purple-500">
+      <span className="motion-safe:animate-pulse text-2xl text-purple-500">
```
Comment (JoshuaKGoldberg) [inline components/NewIssue/NewIssue.tsx:8]: It's important to respect the user's `prefers-reduced-motion` so that the page doesn't show long-running animations if doing so would distract the user, overload their device, or otherwise harm their ability to use the webpage.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

The `motion-safe` Tailwind feature is a nice way to gate on `prefers-reduced-motion`: https://tailwindcss.com/docs/animation#prefers-reduced-motion

File: components/SideNavbar/SideNavbarCategory.tsx [hunk 4]
```diff
@@ -25,15 +25,14 @@ export const SideNavbarCategory: FC<{
 
   if (isOpen) {
     subcategoryList = (
-      <ul className="relative ml-1">
-        <div className="absolute w-0.5 h-full bg-slate-300 dark:bg-slate-700" />
```
Comment (JoshuaKGoldberg) [inline components/SideNavbar/SideNavbarCategory.tsx:29]: Lists (`<ol>`, `<ul>`) must contain only `<li>`, `<script>`, or `<template>` elements. List elements indicate that they contain a list of items, so non-list-item content is semantically weird and confusing.

https://dequeuniversity.com/rules/axe/4.1/list

File: components/popup/index.tsx [hunk 5]
```diff
@@ -20,14 +20,16 @@ const Popup: React.FC<{
     <>
       <Backdrop onClick={onClose} />
       {createPortal(
-        <article
+        <div
```
Comment (JoshuaKGoldberg) [inline components/popup/index.tsx:23]: This one was a little tricky 😄. All page content must be contained in landmarks. When the dialog is showing, it needs something like `role="dialog"` to indicate it's a dialog landmark.

https://dequeuniversity.com/rules/axe/4.7/region?application=AxeChrome

File: components/BackToTop/BackToTopButton.tsx (hunk 1 above)
Comment (rupali-codes) [reply components/BackToTop/BackToTopButton.tsx:50]: Ohh, thanks

File: components/popup/index.tsx [hunk 6]
```diff
@@ -20,14 +20,16 @@ const Popup: React.FC<{
...
             currentCard ? 'animate-scale-appearance' : 'animate-scale-hide'
           } flex h-fit w-[90%] flex-col justify-between gap-5 overflow-hidden rounded-2xl border border-dashed border-violet-600 bg-gray-100 px-5 py-10 dark:bg-gray-900`}
+          role="dialog"
+          title={`${currentCard?.name ?? "Card"} Popup`}
         >
           <div className="flex flex-col gap-5">
-            <header className="flex justify-between items-center">
+            <div className="flex justify-between items-center">
               <div className="w-full flex justify-between items-center">
                 <h2 className="max-w-[80%] text-2xl text-violet-500 capitalize">
```
Comment (rupali-codes) [inline components/popup/index.tsx:34]:
```suggestion
                <h2 className="max-w-[80%] text-2xl text-violet-400 capitalize">
```

File: components/popup/index.tsx [hunk 7]
```diff
@@ -20,14 +20,16 @@ const Popup: React.FC<{
     <>
       <Backdrop onClick={onClose} />
       {createPortal(
-        <article
+        <div
           onClick={(e) => e.stopPropagation()}
           className={`fixed left-1/2 top-1/2 z-[150] max-w-[500px] -translate-x-1/2 -translate-y-1/2 transition-all ${
             currentCard ? 'animate-scale-appearance' : 'animate-scale-hide'
           } flex h-fit w-[90%] flex-col justify-between gap-5 overflow-hidden rounded-2xl border border-dashed border-violet-600 bg-gray-100 px-5 py-10 dark:bg-gray-900`}
```
Comment (rupali-codes) [inline components/popup/index.tsx:27]:
```suggestion
          } flex h-fit w-[90%] flex-col justify-between gap-5 overflow-hidden rounded-2xl border border-dashed border-violet-500 dark:border-violet-400 bg-gray-100 px-5 py-10 dark:bg-gray-900`}
```

File: components/Cards/Card.tsx (hunk 2 above)
Comment (rupali-codes) [reply components/Cards/Card.tsx:11]: Great, we would need to change it for other components  like the _popup_ as well

File: components/NewIssue/NewIssue.tsx (hunk 3 above)
Comment (rupali-codes) [reply components/NewIssue/NewIssue.tsx:8]: I see, thanks

**Review by rupali-codes — COMMENTED** [review]
hey @JoshuaKGoldberg tysm. I have made some suggestions then we are good to go!

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by CBID2 — APPROVED** [review]
LGTM! 😄

**Review by rupali-codes — APPROVED** [review]
looks perfect, thanks a lot!
