### PR TITLE
fix bug: text overlap in search result

### LINKED ISSUE #1218: [Bug] Text overlap in search result.
### Site URL

https://www.linkshub.dev/search?query=front+end+video+with+css+and+javascript

### Issues:
if we search something with long String like this "_front end video with css and javascript"_, it overlaps to all other elements.
 ### Suggestions 

1. if any searches doesn't meet from database, it should write only **no data found**.
2. another is remove that line cause it doesn't looks good when we search like _frame_ . Text appears on screen `SEARCH?QUERY=FRAME` . it seems weird on screen.
 
### Screenshot:
image
image

### Category

Frontend

### Sub Category

Search Result

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Fixes 
Closes #1218 

## Changes proposed

Simply display `#Search: Results Not Found` or `#Search: Results Found`, and it will change based on the click or further interactions. 

### Files modified/added
- `components/TopBar/TopBar.tsx`
- `components/Header/Header.tsx`
- `pages/_app.tsx`
- `pages/search.tsx`
- `hooks/ResultsContext.tsx`

### Before this PR
image

### After this PR
[LinksHub.webm](https://github.com/rupali-codes/LinksHub/assets/130365071/f9b6007d-5842-4f05-aecf-1574dd533bbc)

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by CBID2** [comment]
Hmm... for some reason the deployment build failed. @rupali-codes, can you describe the deployment error? I can't see it because I don't have access to your Vercel account.

**Comment by rupali-codes** [comment]
@harmeetsingh11 and @CBID2 i'm sorry for being late, your vercel deployment is getting failed because of the following error

image

**Comment by harmeetsingh11** [comment]
@rupali-codes , @CBID2 I have fixed the error. Please check it.

**Comment by CBID2** [comment]
> @rupali-codes , @CBID2 I have fixed the error. Please check it.

Can you post another link to your screenshot video @harmeetsingh11? I'm having trouble visualizing the changes you made.

**Comment by harmeetsingh11** [comment]
> > @rupali-codes , @CBID2 I have fixed the error. Please check it.
> 
> Can you post another link to your screenshot video @harmeetsingh11? I'm having trouble visualizing the changes you made.

Sure @CBID2 . Here it is. Please do let me know, in case this doesn't works.

https://github.com/rupali-codes/LinksHub/assets/130365071/eefe912b-aa84-4eef-b901-bdee7ceaf0e7

**Review by rupali-codes — COMMENTED** [review]
Overall it looks great, lets just improve the texts

File: components/TopBar/TopBar.tsx [hunk 1]
```diff
@@ -33,28 +49,78 @@ export const TopBar: FC<{ className?: string | undefined }> = (props) => {
...
-          data-tooltip-place="bottom"
+    <>
+      {regEx.test(category) ? (
+        <div
+          className={`flex items-center text-xl dark:text-gray-300 ${className}`}
+        >
+          <FaSlackHash className="mr-2 text-gray-600 dark:text-gray-300" />
+          <span className="flex uppercase text-gray-900 dark:text-gray-100">
+            {isSearchFound
+              ? `Search: Results Found`
```
Comment (rupali-codes) [inline components/TopBar/TopBar.tsx:60]: when the results are found, can you just write here whatever the search query is? lets say user is searching for **web** so it should show **web** instead of this.

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by harmeetsingh11** [comment]
@rupali-codes I've made the suggested changes. Please review it.

[LinksHub.webm](https://github.com/rupali-codes/LinksHub/assets/130365071/302f31b5-a607-4759-918c-4443bae71aec)

**Review by rupali-codes — APPROVED** [review]
looks perfect to me, thanks a lot!

**Comment by harmeetsingh11** [comment]
Thanks for merging the PR. Can you please add `gssoc23`, `level` labels to it, otherwise my PR won't count.

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @harmeetsingh11. One of the tests had [an error](https://github.com/rupali-codes/LinksHub/pull/1471#pullrequestreview-1569903922). Fix it and tag me when you're ready for another review.

**Comment by harmeetsingh11** [comment]
@CBID2 I've fixed the error. Hope it will work.

**Comment by harmeetsingh11** [comment]
@CBID2 please check.

**Review by CBID2 — DISMISSED** [review]
LGTM

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by rupali-codes — APPROVED** [review]
